-- Day 107: SEO/AEO 详细评分字段 + AI 修复
-- 在 Supabase SQL Editor 中执行

ALTER TABLE seo_audits ADD COLUMN IF NOT EXISTS meta_title TEXT DEFAULT '';
ALTER TABLE seo_audits ADD COLUMN IF NOT EXISTS meta_description TEXT DEFAULT '';
ALTER TABLE seo_audits ADD COLUMN IF NOT EXISTS main_keyword TEXT DEFAULT '';
ALTER TABLE seo_audits ADD COLUMN IF NOT EXISTS keyword_in_title BOOLEAN DEFAULT false;
ALTER TABLE seo_audits ADD COLUMN IF NOT EXISTS keyword_in_content BOOLEAN DEFAULT false;
ALTER TABLE seo_audits ADD COLUMN IF NOT EXISTS has_faq_section BOOLEAN DEFAULT false;
ALTER TABLE seo_audits ADD COLUMN IF NOT EXISTS has_conclusion BOOLEAN DEFAULT false;
ALTER TABLE seo_audits ADD COLUMN IF NOT EXISTS aeo_details JSONB DEFAULT '{}';
ALTER TABLE seo_audits ADD COLUMN IF NOT EXISTS meta_title_score INTEGER DEFAULT 0;
ALTER TABLE seo_audits ADD COLUMN IF NOT EXISTS word_count_score INTEGER DEFAULT 0;
ALTER TABLE seo_audits ADD COLUMN IF NOT EXISTS keyword_score INTEGER DEFAULT 0;
ALTER TABLE seo_audits ADD COLUMN IF NOT EXISTS faq_score INTEGER DEFAULT 0;
ALTER TABLE seo_audits ADD COLUMN IF NOT EXISTS geo_score INTEGER DEFAULT 0;
ALTER TABLE seo_audits ADD COLUMN IF NOT EXISTS faq_schema_json TEXT DEFAULT '';
ALTER TABLE seo_audits ADD COLUMN IF NOT EXISTS geo_summary TEXT DEFAULT '';
